#define VSFUSBH_HCD_TYPE_NUC505			1
#define VSFUSBH_HCD_TYPE_NUC400			2
#define VSFUSBH_HCD_TYPE_STM32F7_HS		3


#define	VSFUSBH_ENABLE					1
#define VSFUSBH_HCD_TYPE				VSFUSBH_HCD_TYPE_NUC505


#if VSFUSBH_ENABLE

#define USB_MAXINTERFACES				4
#define USB_MAXENDPOINTS				8
#define USB_MAXCHILDREN					4
#define USB_ALTSETTINGALLOC				4
#define USB_MAXALTSETTING				32

#if VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_NUC505
	#define USBH_RH_SPEED					USB_SPEED_FULL
	#define USBH_CFG_ENABLE_ISO				0
	#define USBH_CFG_ISO_PACKET_LIMIT		4
#elif VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_NUC400
#elif VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_STM32F7_HS
	#define USBH_RH_SPEED					USB_SPEED_HIGH
	#define USBH_ULPI_EN					1
	#define USBH_CFG_ENABLE_ISO				1
	#define USBH_CFG_ISO_PACKET_LIMIT		4
	#define USBH_HC_AMOUNT					16

	// DWC HOST FIFO CONFIG
	#define USBH_FIFO_LEN							0x1000

	#define USBH_PERIODIC_OUT_PACKET_MAX_SIZE		512
	#define USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE	512
	#define USBH_IN_PACKET_MAX_SIZE					1024

	#if USBH_CFG_ENABLE_ISO
		#define USBH_FIFO_REQUIREMENT_SIZE	((USBH_PERIODIC_OUT_PACKET_MAX_SIZE * 2) + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_IN_PACKET_MAX_SIZE + 4)
		#define USBH_FIFO_EXPECTION_SIZE	((USBH_PERIODIC_OUT_PACKET_MAX_SIZE * 2) + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + (USBH_IN_PACKET_MAX_SIZE + 4) * 2)
	#else
		#define USBH_FIFO_REQUIREMENT_SIZE	(USBH_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_IN_PACKET_MAX_SIZE + 4)
		#define USBH_FIFO_EXPECTION_SIZE	(USBH_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + (USBH_IN_PACKET_MAX_SIZE + 4) * 2)
	#endif

	#if USBH_FIFO_REQUIREMENT_SIZE > USBH_FIFO_LEN
		#error "USBH FIFO SETTING ERROR"
	#elif USBH_FIFO_EXPECTION_SIZE > USBH_FIFO_LEN
		#waning "USBH FIFO WILL RUN IMPERFECT"
	#endif
#elif VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_CMEM7_HS
	#define USBH_RH_SPEED					USB_SPEED_HIGH
	#define USBH_ULPI_EN					0
	#define USBH_CFG_ENABLE_ISO				1
	#define USBH_CFG_ISO_PACKET_LIMIT		4
	#define USBH_HC_AMOUNT					16

	// DWC HOST FIFO CONFIG
	#define USBH_FIFO_LEN							0x1000

	#define USBH_PERIODIC_OUT_PACKET_MAX_SIZE		512
	#define USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE	512
	#define USBH_IN_PACKET_MAX_SIZE					1024

	#if USBH_CFG_ENABLE_ISO
		#define USBH_FIFO_REQUIREMENT_SIZE	((USBH_PERIODIC_OUT_PACKET_MAX_SIZE * 2) + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_IN_PACKET_MAX_SIZE + 4)
		#define USBH_FIFO_EXPECTION_SIZE	((USBH_PERIODIC_OUT_PACKET_MAX_SIZE * 2) + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + (USBH_IN_PACKET_MAX_SIZE + 4) * 2)
	#else
		#define USBH_FIFO_REQUIREMENT_SIZE	(USBH_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_IN_PACKET_MAX_SIZE + 4)
		#define USBH_FIFO_EXPECTION_SIZE	(USBH_PERIODIC_OUT_PACKET_MAX_SIZE + USBH_NON_PERIODIC_OUT_PACKET_MAX_SIZE + (USBH_IN_PACKET_MAX_SIZE + 4) * 2)
	#endif

	#if USBH_FIFO_REQUIREMENT_SIZE > USBH_FIFO_LEN
		#error "USBH FIFO SETTING ERROR"
	#elif USBH_FIFO_EXPECTION_SIZE > USBH_FIFO_LEN
		#waning "USBH FIFO WILL RUN IMPERFECT"
	#endif
#endif

#endif // VSFUSBH_ENABLE
