#ifndef __BCM_CONSTANTS_H_INCLUDED__
#define __BCM_CONSTANTS_H_INCLUDED__

#define BCM_CHIP_BCM43362A2						1

#define BCM_RAM_SIZE							0x3C000

// SPI registers
#define BCM_SPIREG_CONTROL						(uint32_t)0x0000
#define BCM_SPIREG_INTF							(uint32_t)0x0004
#define BCM_SPIREG_INTEN						(uint32_t)0x0006
#define BCM_SPIREG_STATUS						(uint32_t)0x0008
#define BCM_SPIREG_F1INFO						(uint32_t)0x000C
#define BCM_SPIREG_F2INFO						(uint32_t)0x000E
#define BCM_SPIREG_F3INFO						(uint32_t)0x0010
#define BCM_SPIREG_TEST							(uint32_t)0x0014

// BCM_SPIREG_STATUS bits
#define BCM_STATUS_DATA_UNAVIL					(uint32_t)0x00000001
#define BCM_STATUS_FIFO_RD_UNDERFLOW			(uint32_t)0x00000002
#define BCM_STATUS_FIFO_WR_OVERFLOW				(uint32_t)0x00000004
#define BCM_STATUS_F2_INTR						(uint32_t)0x00000008
#define BCM_STATUS_F2_RXRDY						(uint32_t)0x00000020
#define BCM_STATUS_F2_PKGAVAIL					(uint32_t)0x00000100
#define BCM_STATUS_F2_PKGLEN_OFFSET				9
#define BCM_STATUS_F2_PKGLEN_LENGTH				11
#define BCM_STATUS_F2_PKGLEN					(uint32_t)0x00000200

// BCM_SPIREG_INTF bits
#define BCM_INTF_DATA_UNAVIL					(uint32_t)0x0001
#define BCM_INTF_F23_FIFO_RD_UNDERFLOW			(uint32_t)0x0002
#define BCM_INTF_F23_FIFO_WR_OVERFLOW			(uint32_t)0x0004
#define BCM_INTF_COMMAND_ERROR					(uint32_t)0x0008
#define BCM_INTF_DATA_ERROR						(uint32_t)0x0010
#define BCM_INTF_F2_PACKET_AVAIL				(uint32_t)0x0020
#define BCM_INTF_F3_PACKET_AVAIL				(uint32_t)0x0040
#define BCM_INTF_F1_OVERFLOW					(uint32_t)0x0080
#define BCM_INTF_F1_INTR						(uint32_t)0x2000
#define BCM_INTF_F2_INTR						(uint32_t)0x4000
#define BCM_INTF_F3_INTR						(uint32_t)0x8000

// cores
#define BCM_CORE_CHIPCOMMON_BASE				0x18000000
#define BCM_CORE_DOT11MAC_BASE					0x18001000
#define BCM_CORE_SDIOD_BASE						0x18002000
#define BCM_CORE_ARM_BASE						0x18103000
#define BCM_CORE_SOCRAM_BASE					0x18104000

// SDIOD core registers
#define BCM_COREREG_SDIOD_INT_STATUS			(BCM_CORE_SDIOD_BASE + 0x20)
#define BCM_COREREG_SDIOD_INT_HOST_MASK			(BCM_CORE_SDIOD_BASE + 0x24)
#	define BCM_HMB_SW_MASK						0x000000F0
#define BCM_COREREG_SDIOD_FINT_MASK				(BCM_CORE_SDIOD_BASE + 0x34)
#define BCM_COREREG_SDIOD_TO_SB_MAILBOX			(BCM_CORE_SDIOD_BASE + 0x40)
#define BCM_COREREG_SDIOD_TO_SB_MAILBOX_DATA	(BCM_CORE_SDIOD_BASE + 0x48)
#define BCM_COREREG_SDIOD_TO_HOST_MAILBOX_DATA	(BCM_CORE_SDIOD_BASE + 0x4C)

#define BCM_COREREG_AI_IOCTRL					0x408
#define BCM_COREREG_AI_RESETCTRL				0x800

// BCM_COREREG_AI_RESETCTRL bits
#define BCM_RESETCTRL_RESET						1

// BCM_COREREG_AI_IOCTRL bits
#define BCM_IOCTRL_SICF_FGC						0x0002
#define BCM_IOCTRL_SICF_CLOCK_EN				0x0001

// backplane registers
#define BCM_BPREG_SPROM_CS						(uint32_t)0x10000
#define BCM_BPREG_SPROM_INFO					(uint32_t)0x10001
#define BCM_BPREG_SPROM_DATALOW					(uint32_t)0x10002
#define BCM_BPREG_SPROM_DATAHIGH				(uint32_t)0x10003
#define BCM_BPREG_SPROM_ADDRLOW					(uint32_t)0x10004
#define BCM_BPREG_GPIO_SELECT					(uint32_t)0x10005
#define BCM_BPREG_GPIO_OUT						(uint32_t)0x10006
#define BCM_BPREG_GPIO_EN						(uint32_t)0x10007
#define BCM_BPREG_WATERMARK						(uint32_t)0x10008
#	define BCM_SPI_F2_WATERMARK					32
#define BCM_BPREG_DEVICE_CTL					(uint32_t)0x10009
#define BCM_BPREG_SBADDR						(uint32_t)0x1000A
#define BCM_BPREG_FRAMECTRL						(uint32_t)0x1000D
#define BCM_BPREG_CHIPCLKCSR					(uint32_t)0x1000E
#define BCM_BPREG_SDIOPU						(uint32_t)0x1000F
#define BCM_BPREG_WFRAME_BYTECOUNT				(uint32_t)0x10019
#define BCM_BPREG_RFRAME_BYTECOUNT				(uint32_t)0x1001B
#define BCM_BPREG_MESBUSYCTRL					(uint32_t)0x1001D
#define BCM_BPREG_WAKEUPCTRL					(uint32_t)0x1001E
#define BCM_BPREG_SLEEPCSR						(uint32_t)0x1001F

// BCM_BPREG_CHIPCLKCSR bits
#define BCM_CHIPCLKCSR_FORCE_ALP				(uint32_t)0x01
#define BCM_CHIPCLKCSR_FORCE_HT					(uint32_t)0x02
#define BCM_CHIPCLKCSR_FORCE_ILP				(uint32_t)0x04
#define BCM_CHIPCLKCSR_ALP_REQ					(uint32_t)0x08
#define BCM_CHIPCLKCSR_HT_REQ					(uint32_t)0x10
#define BCM_CHIPCLKCSR_FORCE_HW_CLK_OFF			(uint32_t)0x20
#define BCM_CHIPCLKCSR_ALP_AVAIL				(uint32_t)0x40
#define BCM_CHIPCLKCSR_HT_AVAIL					(uint32_t)0x80

// SB registers
#define BCM_SBREG_F1SIG							(uint32_t)0x18000000

#define BCM_INTERFACE_STA						0
#define BCM_INTERFACE_AP						1
#define BCM_INTERFACE_P2P						2

// IO CONTROL
#define BCMIOVAR_TX_GLOM						"bus:txglom"
#define BCMIOVAR_APSTA							"apsta"
#define BCMIOVAR_ETHADDR						"cur_etheraddr"
#define BCMIOVAR_VER							"ver"
#define BCMIOVAR_AMPDU_BA_WSIZE					"ampdu_ba_wsize"
#define BCMIOVAR_AMPDU_MPDU						"ampdu_mpdu"
#define BCMIOVAR_AMPDU_RX_FACTOR				"ampdu_rx_factor"
#define BCMIOVAR_EVT_MSGS						"event_msgs"
#define BCMIOVAR_COUNTRY						"country"
#define BCMIOVAR_BSSCFG_EVT_MSGS				"bsscfg:event_msgs"
#define BCMIOVAR_BSSCFG_SUP_WPA					"bsscfg:sup_wpa"
#define BCMIOVAR_BSSCFG_SUP_WPA2_EAPVER			"bsscfg:sup_wpa2_eapver"
#define BCMIOVAR_ESCAN							"escan"

#define BCMIOCTRL_UP							(uint32_t)2
#define BCMIOCTRL_DOWN							(uint32_t)3
#define BCMIOCTRL_SET_INFRA						(uint32_t)20
#define BCMIOCTRL_SET_AUTH						(uint32_t)22
#define BCMIOCTRL_SET_SSID						(uint32_t)26
#define BCMIOCTRL_GET_CHANNEL					(uint32_t)29
#define BCMIOCTRL_SET_CHANNEL					(uint32_t)30
#define BCMIOCTRL_DISASSOC						(uint32_t)52
#define BCMIOCTRL_SET_GMODE						(uint32_t)110
#define BCMIOCTRL_SET_WSEC						(uint32_t)134
#define BCMIOCTRL_SET_WPA_AUTH					(uint32_t)165
#define BCMIOCTRL_GET_VAR						(uint32_t)262
#define BCMIOCTRL_SET_VAR						(uint32_t)263
#define BCMIOCTRL_SET_SWEC_PMK					(uint32_t)268

// async events
#define BCM_ETHTYPE								0x886C
#define BCM_OUI									"\x00\x10\x18"

#define BCMASYNC_EVT_NONE						-1
#define BCMASYNC_EVT_SET_SSID					0
#define BCMASYNC_EVT_JOIN						1
#define BCMASYNC_EVT_START						2
#define BCMASYNC_EVT_AUTH						3
#define BCMASYNC_EVT_AUTH_IND					4
#define BCMASYNC_EVT_DEAUTH						5
#define BCMASYNC_EVT_DEAUTH_IND					6
#define BCMASYNC_EVT_ASSOC						7
#define BCMASYNC_EVT_ASSOC_IND					8
#define BCMASYNC_EVT_REASSOC					9
#define BCMASYNC_EVT_REASSOC_IND				10
#define BCMASYNC_EVT_DISASSOC					11
#define BCMASYNC_EVT_DISASSOC_IND				12
#define BCMASYNC_EVT_LINK						16
#define BCMASYNC_EVT_ROAM						19
#define BCMASYNC_EVT_PRUNE						23
#define BCMASYNC_EVT_PSK_SUP					46
#define BCMASYNC_EVT_SCAN_RESULT				69
#if BCM_CHIP_BCM43362A2
#	define BCMASYNC_EVT_LAST					87
#endif

#define BCMASYNC_EVT_MASKLEN					((BCMASYNC_EVT_LAST + 7) >> 3)

#define BCMASYNC_SUPSTATUS_OFFSEET				256

enum bcm_async_status_t
{
	BCMASYNC_EVTSTATUS_SUCCESS				= 0,
	BCMASYNC_EVTSTATUS_FAIL					= 1,
	BCMASYNC_EVTSTATUS_TIMEOUT				= 2,
	BCMASYNC_EVTSTATUS_NO_NETWORKS			= 3,
	BCMASYNC_EVTSTATUS_ABORT				= 4,
	BCMASYNC_EVTSTATUS_NO_ACK				= 5,
	BCMASYNC_EVTSTATUS_UNSOLICITED			= 6,
	BCMASYNC_EVTSTATUS_ATTEMPT				= 7,
	BCMASYNC_EVTSTATUS_PARTIAL				= 8,
	BCMASYNC_EVTSTATUS_NEWSCAN				= 9,
	BCMASYNC_EVTSTATUS_NEWASSOC				= 10,
	BCMASYNC_EVTSTATUS_11HQUIET				= 11,
	BCMASYNC_EVTSTATUS_SUPPRESS				= 12,
	BCMASYNC_EVTSTATUS_NOCHANS				= 13,
	BCMASYNC_EVTSTATUS_CCXFASTRM			= 14,
	BCMASYNC_EVTSTATUS_CS_ABORT				= 15,
	
	// SUP status
	BCMASYNC_SUPSTATUS_KEYXCHANGE			= 5 + BCMASYNC_SUPSTATUS_OFFSEET,
	BCMASYNC_SUPSTATUS_KEYED				= 6 + BCMASYNC_SUPSTATUS_OFFSEET,
	BCMASYNC_SUPSTATUS_LAST_BASIC_STATE		= 8 + BCMASYNC_SUPSTATUS_OFFSEET,
};

// WIFI
// ESCAN
#define BCM_WIFI_ESCAN_VER						1
#define BCM_WIFI_SCANACT_START					1
#define BCM_WIFI_SCANACT_CONTINUE				2
#define BCM_WIFI_SCANACT_ABORT					3
#define BCM_WIFI_SCANTYPE_ACTIVE				0x00
#define BCM_WIFI_SCANTYPE_PASSIVE				0x01
#define BCM_WIFI_BSSTYPE_INFRASTRUCTURE			0
#define BCM_WIFI_BSSTYPE_ADHOC					1
#define BCM_WIFI_BSSTYPE_ANY					2

// JOIN
#define BCM_WIFI_AUTH_OPEN						0x00000000
#define BCM_WIFI_AUTH_WEP_ENABLED				0x00000001
#define BCM_WIFI_AUTH_TKIP_ENABLED				0x00000002
#define BCM_WIFI_AUTH_AES_ENABLED				0x00000004
#define BCM_WIFI_AUTH_WSEC_SWFLAG				0x00000008
#define BCM_WIFI_AUTH_SHARED_ENABLED			0x00008000
#define BCM_WIFI_AUTH_WPA_ENABLED				0x00200000
#define BCM_WIFI_AUTH_WPA2_ENABLED				0x00400000
#define BCM_WIFI_AUTH_WPS_ENABLED				0x10000000

#define BCM_WIFI_WPAAUTH_DISABLED				0x00000000
#define BCM_WIFI_WPAAUTH_NONE					0x00000001
#define BCM_WIFI_WPAAUTH_UNSPECIFIED			0x00000002
#define BCM_WIFI_WPAAUTH_PSK					0x00000004

#define BCM_WIFI_WPA2AUTH_UNSPECIFIED			0x00000040
#define BCM_WIFI_WPA2AUTH_PSK					0x00000080

enum bcm_authtype_t
{
	BCM_AUTHTYPE_OPEN			= 0,
	BCM_AUTHTYPE_WEP_PSK		= BCM_WIFI_AUTH_WEP_ENABLED,
	BCM_AUTHTYPE_WEP_SHARED		= BCM_WIFI_AUTH_WEP_ENABLED | BCM_WIFI_AUTH_SHARED_ENABLED,
	BCM_AUTHTYPE_WPA_TKIP_PSK	= BCM_WIFI_AUTH_WPA_ENABLED | BCM_WIFI_AUTH_TKIP_ENABLED,
	BCM_AUTHTYPE_WPA_AES_PSK	= BCM_WIFI_AUTH_WPA_ENABLED | BCM_WIFI_AUTH_AES_ENABLED,
	BCM_AUTHTYPE_WPA2_AES_PSK	= BCM_WIFI_AUTH_WPA2_ENABLED | BCM_WIFI_AUTH_AES_ENABLED,
	BCM_AUTHTYPE_WPA2_TKIP_PSK	= BCM_WIFI_AUTH_WPA2_ENABLED | BCM_WIFI_AUTH_TKIP_ENABLED,
	BCM_AUTHTYPE_WPA2_MIXED_PSK	= BCM_WIFI_AUTH_WPA2_ENABLED | BCM_WIFI_AUTH_TKIP_ENABLED | BCM_WIFI_AUTH_AES_ENABLED,
	BCM_AUTHTYPE_WPS_OPEN		= BCM_WIFI_AUTH_WPS_ENABLED,
	BCM_AUTHTYPE_WPS_SECURE		= BCM_WIFI_AUTH_WPS_ENABLED | BCM_WIFI_AUTH_AES_ENABLED,
	BCM_AUTHTYPE_UNKNOWN		= -1,
};

#endif		// __BCM_CONSTANTS_H_INCLUDED__
