#define VSFUSBH_HCD_TYPE_NUC505			1
#define VSFUSBH_HCD_TYPE_NUC400			2
#define VSFUSBH_HCD_TYPE_STM32F2		3
#define VSFUSBH_HCD_TYPE_STM32F4		4
#define VSFUSBH_HCD_TYPE_STM32F7		5


#define	VSFUSBH_ENABLE					1
#define VSFUSBH_HCD_TYPE				VSFUSBH_HCD_TYPE_NUC505


#if VSFUSBH_ENABLE
#if VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_NUC505
#define USB_MAXINTERFACES				4
#define USB_MAXENDPOINTS				8
#define USB_MAXCHILDREN					4
#define USB_ALTSETTINGALLOC				4
#define USB_MAXALTSETTING				32
#define USB_RH_SPEED					USB_SPEED_FULL
#elif VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_NUC400
#elif VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_STM32F2
#elif VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_STM32F4
#elif VSFUSBH_HCD_TYPE == VSFUSBH_HCD_TYPE_STM32F7
#endif
#endif // VSFUSBH_ENABLE
