#define VSFIP_CFG_ARPCACHE_SIZE				8
#define VSFIP_CFG_ARP_TIMEOUT_MS			1000
#define VSFIP_CFG_TTL_INPUT					10
#define VSFIP_CFG_UDP_PORT					40000
#define VSFIP_CFG_TCP_PORT					40000

#define VSFIP_CFG_TCP_RX_WINDOW				4500
#define VSFIP_CFG_TCP_TX_WINDOW				3000

#define VSFIP_CFG_NETIF_HEADLEN				64
#define VSFIP_CFG_HOSTNAME					"vsfip"

#define VSFIP_SOCKET_NUM					8
#define VSFIP_TCPPCB_NUM					5

#define VSFIP_CFG_TCP_MSS					1460

#define VSFIP_BUFFER_NUM					8
// NETIF_HEAD + 14(ETH_HEAD) + 1500(MTU)
#define VSFIP_BUFFER_SIZE					(1500 + VSFIP_CFG_NETIF_HEADLEN + 14)
